# This is a basic workflow to help you get started with Actions

name: build-docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'doc/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools jupyter-book ghp-import pandas altair vega_datasets==0.8.0

      - name: Build documentation and push to gh-pages
        run: |
          jb build doc
          ghp-import -n -p -f doc/_build/html
